baseURL: "https://www.daninasoft.ro"
languageCode: en-us
summaryLength: "10"
theme: kross-hugo
title: Danina Soft Service
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  home: Acasă
  logo: "images/logo-danina.png"
  theme_color: "#41228e"
  phone: +40 787 521 006
  email: daninasoft@gmail.com
  address: "Str.Zlatnei, Nr.52, Alba Iulia"
  # author: Johnathan Smith
  description: This is meta description
  google_analytics_id: ""
  baidu_site_verification: ""
  baidu_analytics_id: ""
  copyright: "Copyright &copy; 2022 Danina Soft Service"
  preloader:
    enable: true
    preloader: images/preloader.gif
  contact:
    enable: true
    form_action: "https://formsubmit.co/03f93d064acd96464ff51ba1d8d648b6"
  map:
    enable: true
    gmap_api: >-
      https://maps.googleapis.com/maps/api/js?key=AIzaSyAxeYY2udSAyR0xK-bGHQUegkytpllcwb0&#038;types=(cities)&#038;libraries=places&#038;language=ro
    map_latitude: "46.10135"
    map_longitude: "23.55044"
    map_marker: images/marker.png
  cookies:
    enable: true
    expire_days: 2
  social:
    - icon: ti-facebook
      URL: "#"
    - icon: ti-instagram
      URL: "#"
    - icon: ti-dribbble
      URL: "#"
    - icon: ti-twitter-alt
      URL: "#"
menu:
  main:
    - URL: about/
      name: Despre
      weight: 1
    - URL: contact/
      name: Contact
      weight: 4
